# Swagger 2.0 demo used in the REST API Course
# http://www.acloudfan.com
# Part 3 of the incremental creation of the swagger for
# Vacations API for the fictitious enterprise "ACME Travels"

# Swagger 2.0 always begin with the following
swagger: "2.0"

########### Part 1 ###########

# git checkout  rootdocument
# to check the content in part-1

########### Part 2 ########

# git checkout  definitions
# to check the content in part-2

########### Part 3 ########

# This is where the resource paths are defined
paths:
  # Vacation API
  /vacations:
    get:
      description: Returns the collection of valid (i.e., last date >= today's date) vacation packages
      # Refer to the tags created earlier
      security:
        # Array elements needed only in case of OAuth otherwise MUST be empty. In case of OAuth array has the scopes
        - KeySecurity : []
        
      tags:
        - vacations
        - package
      # parameters: There are no parameters for this operation 
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/Vacations"

        "404":
          description: When a vacation package is NOT found
          schema:
            $ref: "#/definitions/NotFoundError"
            
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/GeneralError"
            
  /vacations/{id}:
    get:
      description: Returns the vacation package identified by {id}
      parameters:
        - $ref : "#/parameters/IdInPath"
        
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Vacation"

########### Final Swagger ###

# git checkout  final
# to check the content for final state of the swagger
