swagger: "2.0"

info:
  version: "0.0.1"
  title: ACME Vacations API
  description: This specification is for the ACME Travel packages |
               These specifications were used to teach the students how
               to create the Swagger specifications for their REST API
  contact:
    name: A Cloud Fan
    url: http://www.acloudfan.com
    email: raj@acloudfan.com
    
  license:
    name: GNU
    url: http://acloudfan.com
